name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: howard86/actions/.github/workflows/ci.yml@56841d1894259f87ff5a6551b6ddac457d520b83 # v1.0.2
    permissions:
      contents: read
    with:
      node-version: "24"
      run-test: true
      run-build: false
